# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.66.0
      with:
        ruby-version: 2.3.0

    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Build and Run Project
      run: |
        gem update --system 3.0.9
        gem install bundler -v '2.2.12'
        sudo apt-get install libssl1.0-dev
        bundle config build.puma --with-cflags="-Wno-error=implicit-function-declaration"
        bundle install
        sudo apt-get install postgresql
        rails db:drop
        rails db:create
        rails db:migrate
        rails server & PID=$!
        sleep 30
        kill $PID
