name: Linter

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  evaluate-environment:
    name: Print Environment
    runs-on: ubuntu-latest
    steps:
      - name: Print github workspace
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "pr.ref = ${{github.event.pull_request.head.ref}}"
          echo "github.ref = ${{ github.ref }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  linter:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Config
        run: |
          mkdir -p ${{ github.workspace }}/.github/actions/config
          echo 'versions:\n  - rubocop: "0.81.0"' > ${{ github.workspace }}/.github/actions/config/rubocop.yml
          
      - name: RuboCop
        run: |
          sudo gem install rubocop -v 0.81.0
          rubocop
#      - name: RuboCop Linter
#        uses: andrewmcodes/rubocop-linter-action@v3.3.0
#        with:
#          action_config_path: ".github/actions/config/rubocop.yml"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
